In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('houses.csv')
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
644,5 Bedroom House for sale in Mianwali Colony,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,1.5 Crore,"₹ 11,111/sq.ft.",(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),5 Bedrooms,5 Bathrooms,2 Balconies,NaN,"Mianwali Colony, Gurgaon, Haryana",3 Floors,NaN,10+ Year Old,"['Hanuman Mandir', 'Sheetla Mata Mandir', 'M G...",3 storey independent house for sale,[],"['Centrally Air Conditioned', 'Internet/wi-fi ...","['Environment3.5 out of 5', 'Lifestyle4 out of...",V38945981
580,8 Bedroom House for sale in DLF Phase 3,https://www.99acres.com/8-bhk-bedroom-independ...,NaN,11 Crore,"₹ 28,898/sq.ft.",(354 sq.m.) Plot Area,Plot area 3806.45(353.63 sq.m.)Built Up area: ...,8 Bedrooms,11 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Others","Dlf -3, DLF Phase 3, Gurgaon, Haryana",3 Floors,East,10+ Year Old,NaN,Independent house available for sale.,"['8 Wardrobe', '12 Fan', '1 Exhaust Fan', '8 G...","['Private Garden / Terrace', 'Swimming Pool', ...","['Environment4 out of 5', 'Lifestyle5 out of 5...",Y787895
877,4 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,23 Crore,"₹ 25,556/sq.ft.",(836 sq.m.) Plot Area,Plot area 1000(836.13 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Pooja Room,Store Room,Servant Room","Dlf Phase 1, Gurugram, DLF Phase 1, Gurgaon, H...",2 Floors,South-West,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",1000 sq yards well maintained build up house a...,"['7 Fan', '1 Exhaust Fan', '5 Geyser', '1 Stov...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety5 out of 5', ...",V69736746
845,5 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,8.5 Crore,"₹ 31,481/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),5 Bedrooms,5 Bathrooms,3 Balconies,Servant Room,"B Block, Sushant Lok Phase 1, Gurgaon, Haryana",3 Floors,West,5 to 10 Year Old,"['Huda city centre metro station', 'New Life C...",5bhk duplex kothi available in sushant lok pha...,"['5 Wardrobe', '7 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",V68392090
843,8 Bedroom House for sale in Mayfield Garden,https://www.99acres.com/8-bhk-bedroom-independ...,NaN,5.5 Crore,"₹ 1,087/sq.ft.",(4699 sq.m.) Plot Area,Plot area 5620(4699.04 sq.m.)Built Up area: 82...,8 Bedrooms,8 Bathrooms,2 Balconies,Pooja Room,"12356, Mayfield Garden, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",240sqyd 8bhk servant room ultra luxury kothi p...,"['8 Wardrobe', '9 Fan', '1 Exhaust Fan', '10 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of...",P70096892

In [6]:
# Shape
df.shape

(1044, 21)

In [7]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [8]:
# Check for duplicates
df.duplicated().sum()

13

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(1031, 21)

In [12]:
# Check for missing values
print(df.isnull().sum())

property_name        0
link                 0
society            586
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     453
address             13
noOfFloor           76
facing             369
agePossession       57
nearbyLocations    131
description          8
furnishDetails     299
features           369
rating             137
property_id          8
dtype: int64

In [13]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link', 'property_id'], inplace=True)

In [14]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [15]:
# Rename columns
df.rename(columns={'rate': 'price_per_sqft'}, inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Society

In [16]:
df['society'].value_counts()

society
International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   24
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             13
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Not Applicable                                        7
Uppal Southend4.0 ★                                   7
Sushant Lok 1 Builder Floors                          6
Ansals Palam Vihar                                    6
DLF City Phase 1                                      5
Experion Windchants3.8 ★                              5
DLF Alameda                                           4
Unitech Aspen Greens                                  4
Ansal Sushant Lok Plots4.1 ★                          4
Vatika India Next4.1 ★                                4
nul                                                   4
Malibu Towne                                          3
Eros Rosewood City4.0 ★                               3
Rattan Garden                                         3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
SS Aaron Ville                                        3
Palam Vihar Extension West Zone RWA                   3
Unitech Nirvana Birch Court                           3
Puri Diplomatic Greens4.0 ★                           3
Vatika Signature Villas                               3
Eros Rosewood Villas                                  3
DLF City Plots Phase 3                                3
Central Park Flower Valley                            3
Sector 14 RWA                                         3
DLF New Town Heights 24.0 ★                           3
Anant Raj Estates                                     3
Tata Primanti4.1 ★                                    3
Ansals Florence Villa                                 3
Sobha City                                            2
Ardee City3.8 ★                                       2
Bestech Park View Ananda4.2 ★                         2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Unitech Escape3.8 ★                                   2
SS Hibiscus                                           2
Satya The Hermitage3.5 ★                              2
Hans Enclave                                          2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Project Mianwali Colony                               2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Silverglades Tarudhan Valley Golf Resort              2
Spaze Privy3.9 ★                                      2
Suncity Essel Towers4.2 ★                             2
Luxury DLF City Floors                                2
Emaar Emerald Hills4.1 ★                              2
Ansal API Esencia3.7 ★                                2
shivpuri                                              2
Unitech Deerwood Chase                                2
Om Nagar, Sector-11                                   1
Central Park Flower Valley Cerise Floors              1
Kothi                                                 1
Birla Navya                                           1
Ansal API Spanish Court                               1
private house                                         1
4S Aradhya Homes                                      1
Sector-17C                                            1
Ireo Victory Valley4.1 ★                              1
Ansal Florence Super                                  1
Smart World Orchard                                   1
HUDA Ashok Vihar Phase 13.9 ★                         1
DLF City Plots Phase 4                                1
Ashok Vihar Phase 3 Gurgaon                           1
nirvana country                                       1
Landmark House                                        1
Farrukhnagar                                          1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Prem Kunj                                             1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
Unitech South City 23.8 ★                             1
DLF Floors Phase 3                                    1
huda sector-56 gurgaon                                1
Ireo Victory Valley4.0 ★                              1
Huda Floor                                            1
Huda                                                  1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Grover Homes Sec 4                                    1
DLF Pink Town House4.0 ★                              1
FLOOR WISE DESIGNER KOTHI                             1
Satya The Legend3.8 ★                                 1
Independent House Sector 45                           1
Adani Brahma Samsara4.2 ★                             1
sector 37                                             1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF South City 1                                      1
Ansal Sushant Residency                               1
DLF City Plot Phase 3                                 1
sneh vihar                                            1
DLF The Arbour                                        1
mian wali                                             1
Ansal Celebrity Homes                                 1
Laxmi Garden Sector-11                                1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
Surat nagar phase 2                                   1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
DLF Gardencity Enclave                                1
Rajendra Park Gurgaon                                 1
house number B-34                                     1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
ATS Tourmaline3.9 ★                                   1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
Bhawani enclave                                       1
DLF Garden City Floors                                1
Shri Shyam Residency                                  1
My Home                                               1
Sheetla Enclave                                       1
HUDA Plot Sector 38                                   1
Suncity Avenue 76                                     1
SS Omnia                                              1
secter 16a daultabad faridabad house no 313           1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
rajendra park sec 105                                 1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
Ansal Heights3.2 ★                                    1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
Ninex City                                            1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
Name: count, dtype: int64

In [17]:
df['society'].value_counts().shape

(185,)

In [18]:
import re

df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

0                                        bptp visionnaire
1                                                     nan
2                                                     nan
3                                                     nan
4                                                     nan
5                                                     nan
6                                      emaar mgf marbella
7                                  luxury dlf city floors
8                                                     nan
9                            sushant lok 1 builder floors
10                                                    nan
11                                                    nan
12                                 dlf city plots phase 3
13                                                    nan
14                                                    nan
15                                                    nan
16                                 dlf city plots phase 2
17                                                    nan
18                                         unitech espace
19                                                    nan
20                                                    nan
21                                     emaar mgf marbella
22                                                    nan
23                                     vipul tatvam villa
24                                                    nan
25                                ansal sushant lok plots
26                                     grover homes sec 4
27                                                    nan
28                                                    nan
29                                                    nan
30                                      ansal api esencia
31                                                    nan
32                                                    nan
33                                                    nan
34                                                    nan
35                                                    nan
36                              floor wise designer kothi
37                                                    nan
38                                   suncity essel towers
39                                                    nan
40                                                    nan
41                                              sector 37
42                                                    nan
43                                                    nan
44                                                    nan
45                                                    nan
46                                                    nul
47                                     emaar mgf marbella
48                                       bptp visionnaire
49                                                    nan
50                                                    nan
51                                                    nan
52                                                    nan
53                                    experion windchants
54                                         uppal southend
55                                     vipul tatvam villa
56                                     vipul tatvam villa
57                                                    nan
58                                   dlf new town heights
59                                   dlf new town heights
60                                 puri diplomatic greens
61                                                    nan
62                    international city by sobha phase 2
63                    international city by sobha phase 2
64                                                    nan
65                                                    nan
66                                     emaar mgf marbella
67                                     emaar mgf marbella
68                    international city by sobha phase 2
69                    international city by sobha phase 2
70                    international city by sobha phase 2
71                                    experion windchants
72                                     emaar mgf marbella
73                                     emaar mgf marbella
74                                     emaar mgf marbella
75                                            dlf alameda
76                    international city by sobha phase 1
77                    international city by sobha phase 1
78                    international city by sobha phase 1
79                                                    nan
80                                                    nan
81                                     emaar mgf marbella
82                                     emaar mgf marbella
83                    international city by sobha phase 1
84                    international city by sobha phase 1
85                        all punjabi welfare association
86                                          tata primanti
87                                    experion windchants
88                                      anant raj estates
89                                      anant raj estates
90                    international city by sobha phase 1
91                    international city by sobha phase 2
92                                     vipul tatvam villa
93                                     vipul tatvam villa
94                                     vipul tatvam villa
95                                     vipul tatvam villa
96                                     vipul tatvam villa
97                                            dlf alameda
98                                        eldeco mansionz
99                                        eldeco mansionz
100                                       eldeco mansionz
101                                    emaar mgf marbella
102                                    emaar mgf marbella
103                                    emaar mgf marbella
104                                   emaar emerald hills
105                            central park flower valley
106                                                   nan
107                                                   nan
108                                                   nan
109                                    vipul tatvam villa
110                                puri diplomatic greens
111                                puri diplomatic greens
112                                                   nan
113                                                   nan
114                   international city by sobha phase 1
115                                           dlf alameda
116                   international city by sobha phase 1
117                                                   nan
118                                                   nan
119                                    vipul tatvam villa
120                                                   nan
121                                                   nan
122                                                   nan
123                                                   nan
124                                                   nan
125                                                   nan
126                                                   nan
127                                    vipul tatvam villa
128                                    emaar mgf marbella
129                   international city by sobha phase 2
130                   international city by sobha phase 2
131                   international city by sobha phase 2
132                   international city by sobha phase 2
133                   international city by sobha phase 2
134                                huda sector-56 gurgaon
135                                            sector-17c
136                   international city by sobha phase 1
137                   international city by sobha phase 1
138                                      bptp visionnaire
139                                      bptp visionnaire
140                                                   nan
141                   international city by sobha phase 1
142                   international city by sobha phase 1
143                                                   nan
144                                                   nan
145                                                   nan
146                                                   nan
147                                                   nan
148                                                   nan
149                                                   nan
150                               ansal sushant lok plots
151                   international city by sobha phase 1
152                                                   nan
153                                         private house
154                                                   nan
155                                                   nan
156                                                   nan
157                                                   nan
158                                unitech deerwood chase
159                                  unitech aspen greens
160                                    ansals palam vihar
161                   international city by sobha phase 2
162                   international city by sobha phase 2
163                                      bptp visionnaire
164                   international city by sobha phase 1
165                                                   nan
166                                                   nan
167                                huda ashok vihar phase
168                                                   nan
169                           ashok vihar phase 3 gurgaon
170                                                   nan
171                                                   nan
172                                                   nan
173                                                   nan
174                                          farrukhnagar
175                                                   nan
176                                                   nan
177                                                   nan
178                                                   nan
179                                                   nan
180                                                   nan
181                                             prem kunj
182                                                   nan
183                                                   nan
184                                                   nan
185           secter 16a daultabad faridabad house no 313
186                                                   nan
187                                                   nan
188                                        dlf city plots
189                                                   nan
190                                        not applicable
191                                                   nan
192                                                   nan
193                                                   nan
194                                                   nan
195                                                   nan
196                                                   nan
197                                                   nan
198                                                   nan
199                                  housing board colony
200                                                   nan
201                                                   nan
202                                 rajendra park sec 105
203                                                   nan
204                                              shivpuri
205                                         ansal heights
206                                            ninex city
207                                           spaze privy
208                                                   nan
209                                 signature global park
210                                                   nan
211                                               my home
212                                                   nan
213                                   surat nagar phase 2
214                                                   nan
215                              unitech uniworld resorts
216                                                   nan
217                                                   nan
218                                dlf gardencity enclave
219                                                   nan
220                                 rajendra park gurgaon
221                                                   nan
222                                                   nan
223                                                   nan
224                                                   nan
225                                                   nan
226                                     house number b-34
227                                                   nan
228                                                   nan
229                                                   nan
230                                                   nan
231                                                   nan
232                                                   nan
233                                                   nan
234                                                   nan
235                                                   nan
236                                                   nan
237                                                   nan
238                                                   nan
239                                        ats tourmaline
240                                                   nan
241                                                   nan
242                                       bhawani enclave
243                                                   nan
244                                                   nan
245                                                   nan
246                                                   nan
247                                                   nan
248                                                   nan
249                                                   nan
250                                                   nan
251                                                   nan
252                                                   nan
253                                   om nagar, sector-11
254                                                   nan
255                                                   nan
256                                                   nan
257                                                   nan
258                                                   nan
259                               project mianwali colony
260                                                   nan
261                                                   nan
262                                                   nan
263                                                   nan
264                                                   nan
265                                                   nan
266                                                   nan
267                          project housing board colony
268                                        dlf the arbour
269                                dlf garden city floors
270                                                   nan
271                                                   nan
272                                                   nan
273                              bestech park view ananda
274                                                   nan
275                                                   nan
276                                            huda plots
277                            central park flower valley
278                                           tulip ivory
279                                                   nan
280                                                   nan
281                                                   nan
282                                          malibu towne
283                                  suncity essel towers
284                              emaar mgf the palm drive
285                                                   nan
286                                  bhim nagar, sector 6
287                                                   nan
288                                                   nan
289                                       anamika enclave
290                                                   nan
291                                                   nan
292                   international city by sobha phase 2
293                   international city by sobha phase 2
294                   international city by sobha phase 1
295                   international city by sobha phase 1
296                   international city by sobha phase 1
297                                        not applicable
298                                                   nan
299                                                   nan
300                                                   nan
301                                                   nan
302                                                   nan
303                                                   nan
304                                                   nan
305                                                   nan
306                                                   nan
307                                                   nan
308                                                   nan
309                                                   nan
310                                                   nan
311                                                   nan
312                                                   nan
313                                                   nan
314                                                   nan
315                                                   nan
316                                                   nan
317                                                   nan
318                                                   nan
319                                                   nan
320                                                   nan
321                                                   nan
322                                                   nan
323                                         manohar nagar
324                                                   nan
325                                                   nan
326                                                   nan
327                                                   nan
328                                                   nan
329                                                   nan
330                                                   nan
331                                 vatika sovereign next
332                                                   nan
333                                                   nan
334                                                   nan
335                                                   nan
336                                                   nan
337                                                   nan
338                                                   nan
339                                                   nan
340                                                   nan
341                                                   nan
342                                                   nan
343                                                   nan

In [19]:
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()
df['society'].value_counts().shape

(183,)

In [20]:
df['society'] = df['society'].str.replace('nan', 'independent')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Price

In [21]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
5 Crore             13
4.5 Crore           13
70 Lac              13
8 Crore             13
50 Lac              13
75 Lac              13
8.5 Crore           12
7 Crore             12
85 Lac              12
1.5 Crore           11
4 Crore             11
10 Crore            10
Price on Request    10
45 Lac              10
2.25 Crore          10
2.5 Crore           10
60 Lac              10
90 Lac              10
9 Crore             10
9.5 Crore            9
12 Crore             9
80 Lac               9
1.7 Crore            9
2 Crore              9
1.1 Crore            9
1 Crore              8
6.75 Crore           8
11 Crore             8
1.6 Crore            8
4.6 Crore            8
1.3 Crore            7
95 Lac               7
12.5 Crore           7
3.75 Crore           7
1.2 Crore            7
55 Lac               7
2.1 Crore            7
65 Lac               7
40 Lac               7
1.35 Crore           7
1.15 Crore           6
10.5 Crore           6
4.25 Crore           6
7.5 Crore            6
16 Crore             6
3.25 Crore           6
2.95 Crore           6
5.7 Crore            6
2.75 Crore           6
13.5 Crore           6
3.6 Crore            6
1.45 Crore           6
6.25 Crore           6
38 Lac               5
3 Crore              5
4.75 Crore           5
15 Crore             5
35 Lac               5
5.6 Crore            5
1.8 Crore            5
1.25 Crore           5
2.8 Crore            5
7.25 Crore           5
42 Lac               4
2.4 Crore            4
1.65 Crore           4
4.35 Crore           4
4.7 Crore            4
18 Crore             4
9.25 Crore           4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
8.25 Crore           4
5.75 Crore           4
11.5 Crore           4
6.8 Crore            4
17 Crore             4
3.2 Crore            4
5.8 Crore            4
13 Crore             4
3.3 Crore            4
1.16 Crore           3
2.3 Crore            3
82 Lac               3
1.9 Crore            3
5.65 Crore           3
7.35 Crore           3
4.3 Crore            3
92 Lac               3
1.85 Crore           3
34 Lac               3
3.4 Crore            3
32 Lac               3
49 Lac               3
5.15 Crore           3
62 Lac               3
8.4 Crore            3
2.2 Crore            3
19 Crore             3
4.45 Crore           3
6.95 Crore           3
6.4 Crore            3
20 Crore             3
1.95 Crore           3
3.1 Crore            3
7.2 Crore            3
2.9 Crore            3
1.55 Crore           3
3.85 Crore           3
9.9 Crore            2
11.75 Crore          2
7.1 Crore            2
4.95 Crore           2
14 Crore             2
8.49 Crore           2
1.05 Crore           2
3.51 Crore           2
3.35 Crore           2
89 Lac               2
10.85 Crore          2
26 Crore             2
58.25 Lac            2
3.65 Crore           2
10.55 Crore          2
15.5 Crore           2
3.15 Crore           2
2.15 Crore           2
6.3 Crore            2
2.55 Crore           2
11.25 Crore          2
36 Lac               2
66 Lac               2
48 Lac               2
1.75 Crore           2
11.95 Crore          2
67 Lac               2
58 Lac               2
19.5 Crore           2
3.05 Crore           2
3.55 Crore           2
30 Lac               2
10.45 Crore          2
6.15 Crore           1
2.47 Crore           1
55.11 Lac            1
3.7 Crore            1
8.45 Crore           1
4.4 Crore            1
99 Lac               1
2.65 Crore           1
1.27 Crore           1
11.29 Crore          1
7.05 Crore           1
4.31 Crore           1
18.4 Crore           1
3.69 Crore           1
10.3 Crore           1
9.4 Crore            1
7.3 Crore            1
18.5 Crore           1
5.85 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
4.02 Crore           1
5.1 Crore            1
3.9 Crore            1
2.01 Crore           1
5.88 Crore           1
52.75 Lac            1
46.75 Lac            1
12.25 Crore          1
11.3 Crore           1
8.48 Crore           1
11.58 Crore          1
3.49 Crore           1
8.2 Crore            1
61 Lac               1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
5.35 Crore           1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
4.99 Crore           1
9.8 Crore            1
5.51 Crore           1
9.01 Crore           1
4.15 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
1.04 Crore           1
9.85 Crore           1
1.18 Crore           1
15.1 Crore           1
5.9 Crore            1
3.99 Crore           1
22 Crore             1
47 Lac               1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
5.2 Crore            1
7.99 Crore           1
42.75 Lac            1
71 Lac               1
7.6 Crore            1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
10.75 Crore          1
29 Lac               1
4.12 Crore           1
52 Lac               1
4.49 Crore           1
53 Lac               1
7.5 Lac              1
2.58 Crore           1
7.49 Crore           1
22 Lac               1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
63 Lac               1
1.87 Crore           1
1.72 Crore           1
5.46 Crore           1
12.39 Crore          1
78 Lac               1
1.52 Crore           1
10.56 Crore          1
5.4 Crore            1
24 Lac               1
44 Lac               1
83 Lac               1
17.3 Crore           1
3.93 Crore           1
27 Lac               1
8.1 Crore            1
8.7 Crore            1
14.75 Crore          1
9.54 Crore           1
6.2 Crore            1
18.9 Crore           1
98 Lac               1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.12 Crore           1
6.81 Crore           1
8.81 Crore           1
8.9 Crore            1
7.69 Crore           1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
15.5 Lac             1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
13 Lac               1
96 Lac               1
6.6 Crore            1
18.02 Crore          1
65.8 Lac             1
8.8 Crore            1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
2.98 Crore           1
Name: count, dtype: int64

In [23]:
df = df[df['price'] != 'Price on Request']
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [25]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0]) / 100, 2)
        else:
            return round(float(x[0]), 2)

In [26]:
df['price'] = df['price'].str.split(' ').apply(treat_price)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### price_per_sqft

In [27]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     11
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 26,667/sq.ft.      6
₹ 13,333/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 9,444/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 23,148/sq.ft.      5
₹ 11,100/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 35,000/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 18,889/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 36,111/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 14,815/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 11,250/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 32,222/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 12,500/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 7,407/sq.ft.       2
₹ 35,185/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 9,000/sq.ft.       2
₹ 20,635/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 35,556/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 44,444/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 75,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 17,037/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 4,444/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 13,622/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 20,988/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 18,888/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 18,444/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 234,375/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 22,812/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 178,571/sq.ft.     1
₹ 23,240/sq.ft.      1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,127/sq.ft.       1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 7,555/sq.ft.       1
₹ 6,289/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 17,857/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 20,444/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 20,026/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 31,915/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 23,442/sq.ft.      1
₹ 33,665/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 6,230/sq.ft.       1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 5,128/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 144,444/sq.ft.     1
₹ 20,349/sq.ft.      1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 19,360/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 18,620/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 15,432/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 19,231/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 17,187/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 10,579/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 16,056/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 40,850/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 14,222/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,125/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 6,800/sq.ft.       1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 7,333/sq.ft.       1
₹ 20,115/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,701/sq.ft.       1
₹ 4,117/sq.ft.       1
₹ 7,309/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,695/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 14,890/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 14,729/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 17,650/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 38,667/sq.ft.      1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 20,062/sq.ft.      1
₹ 98,214/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 19,818/sq.ft.      1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,397/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 3,254/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 8,642/sq.ft.       1
₹ 10,122/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 22,297/sq.ft.      1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 5,658/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 8,796/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 66,666/sq.ft.      1
₹ 19,869/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 120,000/sq.ft.     1
₹ 125,000/sq.ft.     1
₹ 37,313/sq.ft.      1
₹ 73,333/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 11,718/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 35,494/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 33,129/sq.ft.      1
Name: count, dtype: int64

In [32]:
df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',', '').str.strip().astype('float')

0        20115.0
1       105751.0
2        38251.0
3        43066.0
4        53763.0
5        39062.0
6        37037.0
7        48889.0
8        38150.0
9        10077.0
10       32963.0
11       27778.0
12       34083.0
13       33200.0
14       30556.0
15       14914.0
16       29861.0
17       23333.0
18       41762.0
19       15451.0
20       12938.0
21       38095.0
22       25926.0
23       26235.0
24       38760.0
25       25926.0
26        9374.0
27       13410.0
28       21124.0
29       32593.0
30       24170.0
31       37037.0
32       28490.0
33      122222.0
34       13542.0
35       19097.0
36       48148.0
37       22222.0
38       22222.0
39       33333.0
40       32222.0
41        7290.0
42       27741.0
43       50000.0
44       43534.0
45       45889.0
46       34722.0
47           NaN
48       20690.0
49       29716.0
50       16378.0
51       17284.0
52       37777.0
53       12519.0
54       25562.0
55       27971.0
56       21000.0
57       24500.0
58        7058.0
59        7058.0
60       11250.0
61       23333.0
62       13622.0
63       13909.0
64       20000.0
65       35400.0
66       16058.0
67       16058.0
68       13623.0
69       13910.0
70       13910.0
71       12027.0
72       15700.0
73       19708.0
74       16039.0
75       13331.0
76       11100.0
77       11100.0
78       11100.0
79       40135.0
80       16244.0
81       19708.0
82       16039.0
83       11100.0
84       11100.0
85       16999.0
86       10714.0
87       12027.0
88           NaN
89           NaN
90       21605.0
91       10463.0
92       18750.0
93       19000.0
94       27793.0
95       22006.0
96       19000.0
97       13333.0
98       22222.0
99       28760.0
100      16975.0
101      41615.0
102      16058.0
103      15700.0
104          NaN
105          NaN
106      14444.0
107      10101.0
108      38703.0
109      22222.0
110      12828.0
111      12842.0
112      23148.0
113       8557.0
114      16428.0
115          NaN
116      10556.0
117      13519.0
118      42032.0
119      24069.0
120      21605.0
121      13889.0
122      14650.0
123      13889.0
124      13778.0
125      15625.0
126      23333.0
127      21250.0
128      38667.0
129      26667.0
130      12593.0
131      26389.0
132      12963.0
133      25514.0
134      24845.0
135      17650.0
136      24280.0
137      26423.0
138       6666.0
139       8916.0
140      36667.0
141       9000.0
142      20000.0
143       9028.0
144       4074.0
145        630.0
146      86567.0
147      92857.0
148     100000.0
149      88157.0
150      29974.0
151      24691.0
152       2778.0
153      46906.0
154      25000.0
155      23699.0
156      25960.0
157      28424.0
158      33333.0
159       4490.0
160      14729.0
161      25111.0
162      25000.0
163       7309.0
164      10556.0
165      74074.0
166      12000.0
167      10233.0
168      26852.0
169       8878.0
170      14286.0
171       8928.0
172       8007.0
173      11111.0
174       5698.0
175      28283.0
176      24214.0
177      26613.0
178     138888.0
179      10000.0
180       7666.0
181       7407.0
182       8333.0
183       4666.0
184      13333.0
185      60000.0
186      11111.0
187       7778.0
188      40775.0
189      99173.0
190      12222.0
191       6172.0
192      22222.0
193       9111.0
194      80357.0
195       4117.0
196       7308.0
197       8701.0
198       8000.0
199      25926.0
200       6666.0
201       2296.0
202       8888.0
203      33333.0
204      12444.0
205       9793.0
206       6250.0
207       8486.0
208      11717.0
209       7589.0
210      13333.0
211      12592.0
212      15384.0
213       7843.0
214      22222.0
215      23333.0
216      29336.0
217      10288.0
218      11284.0
219      11029.0
220      10277.0
221       6944.0
222       8518.0
223      10555.0
224      11250.0
225        557.0
226       8888.0
227      11852.0
228       8947.0
229      39265.0
230       6083.0
231     230547.0
232       8411.0
233      32291.0
234      41666.0
235       8889.0
236       7280.0
237      90000.0
238      10089.0
239       8697.0
240       8500.0
241       9333.0
242       8235.0
243      13333.0
244      21667.0
245      20425.0
246       5472.0
247       6944.0
248      57692.0
249      60000.0
250          NaN
251       3857.0
252      21759.0
253       8333.0
254       7407.0
255      75000.0
256      10482.0
257      25386.0
258       8735.0
259       9444.0
262      20000.0
263      18667.0
264      18889.0
265       2525.0
266      24306.0
267      17695.0
268      21519.0
269      17817.0
270          2.0
271       6173.0
272      55000.0
273          NaN
274      13888.0
275      20323.0
276      20359.0
277          NaN
278          NaN
279       5833.0
280      11693.0
281      26667.0
282      53125.0
283      17900.0
284          NaN
285      39886.0
286     126865.0
287      40909.0
288      27155.0
289      14492.0
292      13622.0
293      14045.0
294      10783.0
295      10804.0
296      10783.0
297      14167.0
298      11111.0
299          NaN
300      13157.0
301       5888.0
302      11111.0
303       7875.0
304       9654.0
305       4808.0
306       8222.0
307      11111.0
308       3857.0
309      50000.0
310      11273.0
311       8000.0
312       7627.0
313       5666.0
314       5000.0
315       5000.0
316       6567.0
317      22068.0
318      13333.0
319       6666.0
320      66666.0
321       7500.0
322       8386.0
323      12444.0
324      25000.0
325       6944.0
326          NaN
327      11111.0
328      28674.0
329       9725.0
330      21111.0
331       7500.0
332      10784.0
333      12162.0
334       8910.0
335      10518.0
336      19869.0
337       8796.0
338       9722.0
339       7522.0
340       5658.0
341       5000.0
342      24545.0
343       7701.0
344       8235.0
345      14072.0
346      26000.0
347      24305.0
348      19286.0
349      22634.0
350      26570.0
351      11111.0
352       6410.0
353     133079.0
354      15257.0
356       5778.0
357       6111.0
358      15625.0
359      78125.0
360      17955.0
361       7916.0
362     211111.0
363      80000.0
364      35000.0
365      10000.0
366     120000.0
367      22297.0
368     125000.0
369       8889.0
370      73333.0
371          NaN
372      11111.0
373      26235.0
374       6790.0
375      20833.0
376     315789.0
377      10224.0
378       3500.0
379       3285.0
380      74000.0
381      27139.0
382      10000.0
383       5555.0
385      23662.0
386      17574.0
387      13333.0
388      10753.0
389       9091.0
390      23557.0
391      59259.0
392     105263.0
393      21195.0
394        151.0
395      25103.0
396      13889.0
397      14954.0
398      23333.0
399       8784.0
400       6500.0
401      35494.0
402      11464.0
403      11718.0
404      11555.0
405      50000.0
406       3874.0
407       7576.0
408      11556.0
409      10753.0
410      20635.0
411      10378.0
412      11888.0
413      17284.0
414      32258.0
415      11111.0
416      12222.0
417      16389.0
418      31506.0
419       9722.0
420      12820.0
421     229885.0
422      10000.0
423       8889.0
424      12400.0
425       9259.0
426        232.0
427      15257.0
428     218750.0
429      54794.0
430      14245.0
431       6367.0
432      37313.0
433      90909.0
434       9444.0
435       5000.0
436          NaN
437      10122.0
438      10000.0
439       8642.0
440       6481.0
441       6707.0
442     245398.0
443       9259.0
444          NaN
445      11904.0
446       9135.0
448       7111.0
449       8012.0
450     183333.0
451      12500.0
452      10142.0
453       8444.0
454       8125.0
455      14583.0
456      17037.0
457      11538.0
458       8730.0
459      12222.0
460      14444.0
461      11574.0
462          NaN
463      26667.0
464      11111.0
465       8230.0
466      13095.0
467      30556.0
468      11852.0
469      10000.0
470      29311.0
471      11250.0
472      30384.0
473       8444.0
474      19818.0
475       1992.0
476       7619.0
477      98214.0
478      13499.0
479       7820.0
480       5555.0
481       4000.0
482      14720.0
483       5664.0
484      19753.0
485      76000.0
486      37037.0
487      63492.0
488       9000.0
489       4444.0
490       2500.0
491       6667.0
492       3704.0
493      12777.0
494       6648.0
495      11407.0
496      20233.0
497      17778.0
498      20062.0
499      11494.0
500      25543.0
501      12343.0
502      16892.0
503       8000.0
504      17500.0
505       3904.0
506      14323.0
507       4222.0
508     181818.0
509      75000.0
510      26620.0
511       5555.0
512      10000.0
513       9722.0
514       9500.0
515      17937.0
516       3254.0
517       5333.0
518      30556.0
519       4583.0
520      12500.0
521      21875.0
523      16667.0
524       7075.0
525       8078.0
526       4251.0
527      17584.0
528       5397.0
529       9074.0
530       5583.0
531       3519.0
532      11194.0
533     100000.0
534       6981.0
535       6702.0
536       9444.0
537      10556.0
538      18333.0
539       4877.0
540       7479.0
541       7400.0
542      16003.0
543       8000.0
544       9444.0
545       9103.0
546       7727.0
547      45710.0
549       8702.0
550       5950.0
551       3500.0
552       9722.0
553       8889.0
554      26973.0
555      32407.0
556      13750.0
557       6000.0
558      14890.0
559       9210.0
560       6800.0
561      10518.0
562       7333.0
563       8101.0
564       6944.0
565      14184.0
566       4260.0
567      10582.0
568       9390.0
569      84000.0
570       6938.0
571      15555.0
572      33333.0
573       7539.0
574      10000.0
575      10067.0
576       1649.0
577      10000.0
578      10000.0
579      13000.0
580      28898.0
581      28200.0
582       7168.0
583      20444.0
584          NaN
585      35185.0
586       6289.0
587      17857.0
588       7000.0
589      14166.0
590      30968.0
591       7777.0
592      18658.0
593      10484.0
594     160000.0
595       8127.0
596       5000.0
597       8000.0
598       7555.0
599      49500.0
600       8889.0
601      13030.0
602     308333.0
603       8333.0
604      10610.0
605      18889.0
606       7302.0
607       8155.0
608      10591.0
609      24074.0
610      14815.0
611       5160.0
612     144444.0
613       9615.0
614       9444.0
615      10101.0
616      22222.0
617      32407.0
618       6813.0
619      15046.0
620      11583.0
622       6034.0
623      10085.0
624      17778.0
625      40611.0
626      29630.0
627      29629.0
628      10740.0
629       4444.0
630      17980.0
631      55000.0
632      19737.0
633       5093.0
634      25463.0
635      12000.0
636       7007.0
637       8920.0
638      35294.0
639      12963.0
640       8254.0
641       5128.0
642       5777.0
643      15926.0
644      11111.0
645      14285.0
646      34307.0
647      51864.0
648      44265.0
649      29444.0
650      39074.0
651      38734.0
652      23442.0
653      41833.0
654      27778.0
655     600000.0
656      23889.0
657      25000.0
658      10260.0
659      31915.0
660      11102.0
661       8866.0
662      36911.0
663      36111.0
664      15444.0
665      11240.0
666      15437.0
667      14351.0
668      27191.0
669     241666.0
670      32963.0
671      33592.0
672      24455.0
673      26667.0
674      26389.0
675     194444.0
676      18444.0
677      11600.0
678      38095.0
679      13492.0
680      33951.0
681      11157.0
682       8444.0
683      21495.0
684      42054.0
685       1560.0
686      20741.0
687      13178.0
688      12000.0
689      26428.0
690      82540.0
691      18888.0
692      31481.0
693      13501.0
694      20988.0
695     400000.0
696      21296.0
697      34722.0
698      18626.0
699      24366.0
700      26298.0
701       7500.0
702      24171.0
703      23000.0
704      29697.0
705      33333.0
706      36111.0
707       6778.0
708      22812.0
709     261194.0
710     178571.0
711      27461.0
712      31686.0
713      22222.0
714      23061.0
715      32222.0
716      17662.0
717      39841.0
718      37627.0
719      23148.0
720      29880.0
721      20068.0
722      16569.0
723      21242.0
724      11574.0
725      32562.0
726      13000.0
727      22429.0
728      39530.0
729      22222.0
730      38889.0
731          NaN
732      57206.0
733      27222.0
734      63554.0
735      10601.0
736      20940.0
737      32253.0
738      37037.0
739          NaN
740      23704.0
741      23693.0
742      15989.0
743      19268.0
744      19360.0
745      45833.0
746      29880.0
747      23437.0
748       2716.0
749      39841.0
750      32222.0
751      40850.0
752      12342.0
753      15555.0
754      26111.0
755      31790.0
756      24691.0
757     235376.0
758      29293.0
759      16004.0
760      27333.0
761      17624.0
762      38580.0
763      27778.0
764      35556.0
765      38580.0
766      35000.0
767      30864.0
768          NaN
769     161849.0
770      27778.0
771      16056.0
772      17707.0
785       7718.0
786      25535.0
787       1859.0
788      17037.0
789      10579.0
790      42194.0
791      15625.0
792      15278.0
793     201388.0
794      17187.0
795          NaN
796      44444.0
797      18928.0
798      10926.0
799      19608.0
800       8089.0
801       6849.0
802      24691.0
803          NaN
804      19607.0
805      40000.0
806      34846.0
807      31444.0
808      26235.0
809      22222.0
810      23457.0
811      27083.0
812      43210.0
813      31926.0
814      38611.0
815      27911.0
816      29022.0
817      12837.0
818      12198.0
819      35741.0
820          NaN
821      16666.0
822      35556.0
823       9634.0
825      31481.0
826       7827.0
827      38760.0
828      23556.0
829      10035.0
830      28841.0
831      26615.0
832      24155.0
833      14815.0
834      22222.0
835      62222.0
836       6597.0
837       7870.0
838      26852.0
839      28233.0
840      15111.0
841      34722.0
842      19820.0
843       1087.0
844          NaN
845      31481.0
846      26235.0
847      19645.0
848      36883.0
849      37037.0
850      27871.0
851      35109.0
852      17692.0
853      38022.0
854      33333.0
855      25309.0
856      16990.0
857      14222.0
858      22222.0
859      16388.0
860      22075.0
861      11666.0
862      47167.0
863       7937.0
864      20197.0
865      20635.0
866      34037.0
867      10123.0
868      28858.0
869      28549.0
870      15555.0
871      13513.0
872      20769.0
873      34568.0
874      21097.0
875      33951.0
876      24306.0
877      25556.0
878      36111.0
879       7756.0
880      21825.0
881      12342.0
882      16577.0
883      17706.0
884      29074.0
885      29880.0
886      42222.0
887      38194.0
888      21605.0
889      38194.0
890      37778.0
891      31111.0
892      17213.0
893      18620.0
894      17014.0
895       7750.0
896       7172.0
897      29638.0
898      33333.0
899       8137.0
900       7582.0
901      48148.0
902      18605.0
903      16066.0
904      55556.0
905      38986.0
906      24510.0
907      11428.0
908      22184.0
909      30247.0
910      20370.0
911      31666.0
912      18889.0
913     283333.0
914      31481.0
915      42222.0
916      59259.0
917      45833.0
918      18008.0
919      26235.0
920          NaN
921      33333.0
922      12285.0
923      19293.0
924      20599.0
925     173992.0
926      21367.0
927      20299.0
928      41818.0
929       9634.0
930      19231.0
931      20833.0
932      33333.0
933       6875.0
934      14667.0
935      14787.0
936      16319.0
937      18250.0
938      27390.0
939      30728.0
940      35000.0
941      30556.0
942      41315.0
943       3786.0
944      60000.0
945      24691.0
946       9349.0
947      23504.0
948      21605.0
949     234375.0
950      26235.0
951      21786.0
952      35000.0
953       8235.0
954      15432.0
955      37627.0
956      21251.0
957      30556.0
958      27160.0
959      35530.0
960      22046.0
961      22222.0
962      33333.0
963      27132.0
964      22855.0
965      40741.0
966      34722.0
967      29333.0
968      32328.0
969     290948.0
970      25562.0
971      12393.0
972      22331.0
973      20317.0
974      18088.0
975      21759.0
976      16600.0
977      21219.0
978      19125.0
979      18885.0
980      15000.0
981      37037.0
982      18814.0
983      32328.0
984      23457.0
985      16975.0
986      18889.0
987      14000.0
988      32407.0
989     266666.0
990      26502.0
991      23148.0
992      32407.0
993      33951.0
994      18808.0
995      31481.0
996      10838.0
997      19847.0
998      23148.0
999      12037.0
1000     17820.0
1001     24390.0
1002     35185.0
1003         NaN
1004     26063.0
1005     79365.0
1006     23932.0
1007     24573.0
1008     24005.0
1009     32870.0
1010     33404.0
1011     23240.0
1012     29630.0
1013     16071.0
1014     51440.0
1015     26667.0
1016     28782.0
1017     34491.0
1018     34351.0
1019     47803.0
1020      6230.0
1021     33665.0
1022     44444.0
1023         NaN
1024         NaN
1025     20566.0
1026     22222.0
1027     26667.0
1028     20349.0
1029     23148.0
1030     21124.0
1031     24202.0
1032     24155.0
1033     23870.0
1034     24500.0
1035     24845.0
1036     20026.0
1037     28787.0
1038     12551.0
1039     30556.0
1040     31481.0
1041     33333.0
1042     33129.0
1043     14815.0
Name: price_per_sqft, dtype: float64

In [33]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',', '').str.strip().astype('float')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### bedrooms

In [34]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [38]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
62,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
63,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
66,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
67,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
68,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
69,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
70,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
71,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
72,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
73,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
74,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
75,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
76,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
77,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
78,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
83,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
86,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
87,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
88,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
89,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
92,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
93,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
96,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
98,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
99,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
100,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
103,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
104,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
110,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
115,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
273,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
277,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
278,6 Bedroom House for sale in Sector 70 Gurgaon,tulip ivory,NaN,NaN,(697 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 70 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Tulip ivory in sector-70, gurgaon by tulip inf...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
284,3 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf the palm drive,NaN,NaN,(353 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf the palm drive in sector-66, gurgaon...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
292,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(540 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
293,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,14045.0,(363 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
294,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
295,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10804.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,10783.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
318,3 Bedroom House for sale in Arjun Nagar,independent,NaN,13333.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,2 Bedroom House for sale in Palam Vihar Extension,independent,NaN,6666.0,(49 sq.m.) Carpet Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,2 Bedroom House for sale in Rajiv Nagar,independent,NaN,66666.0,(7 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,7 Bedroom House for sale in Surya Vihar,independent,NaN,7500.0,(372 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,2 Bedroom House for sale in Sector 5 Gurgaon,independent,NaN,25000.0,(93 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,4 Bedroom House for sale in Sohna,independent,NaN,6944.0,(167 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,4 Bedroom House for sale in Sector 52 Gurgaon,independent,NaN,NaN,(201 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,6 Bedroom House for sale in Sector 22 Gurgaon,saksham welfare association,NaN,19645.0,(220 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# Deleting above ones because they have a lot of missing values
df = df[~df['bedRoom'].isnull()]
df.shape

(964, 19)

In [ ]:
df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [42]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Bathroom

In [43]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: count, dtype: int64

In [44]:
df['bathroom'].isnull().sum()

0

In [47]:
df['bathroom'].str.split(' ').str.get(0).astype('int')

0        4
1        4
2       10
3       21
4       12
5       20
6        5
7       16
8        6
9        4
10       3
11       7
12      13
13       6
14       6
15       4
16       9
17       7
18       4
19       6
20       9
21       6
22       4
23       4
24       9
25       5
26       5
27       9
28       9
29       5
30       5
31       6
32      10
33       4
34       2
35       4
36      16
37       3
38       4
39       5
40       5
41       1
42      12
43      16
44      12
45      18
46       5
47       5
48       5
49       4
50       3
51       6
52       8
53       6
54       6
55       4
56       5
57       4
58       4
59       4
60       5
61       3
64       5
65       4
79      12
80       4
90       4
91       4
101      4
106      3
107      3
108      5
109      6
112      5
113      2
114      4
116      5
117      3
118     13
119      5
120      4
121      2
122      4
123      2
124      3
125      3
126      4
127      5
128      5
129      6
130      5
131      6
132      6
133      5
134      5
135      5
136      5
137      5
138      4
139      4
140      7
141      5
142      6
143      2
144      3
145      3
146      2
147      1
148      2
149      3
150      6
151      5
152      9
153     18
154     16
155      4
156      7
157      1
158      4
159      3
160      5
161      5
162      5
163      4
164      4
165      7
166      1
167      2
168      3
169      3
170      9
171      1
172      2
173      3
174      4
175      7
176     17
177      4
178      1
179      4
180      7
181      4
182      3
183      2
184      3
185      2
186      3
187      2
188      3
189      4
190      3
191      8
192      5
193      3
194      3
195      4
196      3
197      4
198      1
199      6
200      8
201      1
202      5
203      5
204      7
205      4
206      4
207      5
208      4
209      2
210      4
211      2
212      6
213      2
214      3
215      7
216      8
217      3
218      2
219      5
220      3
221     10
222      3
223      2
224      3
225      4
226      2
227      5
228      6
229      5
230      2
231     10
232      2
233      6
234      4
235      1
236      6
237      3
238      3
239      4
240      1
241      3
242      3
243      4
244      6
245      4
246      2
247     36
248      2
249      3
250      4
251      3
252      3
253      2
254      2
255      9
256      3
257      6
258      6
259      1
262      4
263      4
264      2
265      1
266      3
267      2
268      4
269      7
270      3
271      3
272      3
274      5
275      2
276      2
279      2
280      4
281      5
282     12
283      6
285      9
286      2
287      5
288      6
289      9
297      4
298      4
299      2
300      5
301      2
302      2
303      2
304     10
305      1
306      2
307      3
308      6
309      2
310      1
311      9
312      5
313      4
314      1
315      1
316      2
317      2
322      3
323     34
327      2
328      6
329      4
330      1
331      6
332      2
333      4
334      2
335      2
336      2
337      2
338      2
339      3
340      2
341      2
342      3
343      2
344      2
345      5
346      5
347      5
348      9
349      9
350      1
351      2
352      2
353      8
354      1
356      2
357      4
358      4
359      3
360      3
361      1
362      4
363      6
364      2
365      4
366      3
367      4
368      4
369      4
370      2
371      1
372      4
373      6
374      3
375      4
376      6
377      4
378      4
379      2
380      3
381      6
382      5
383      1
385      4
386      5
387      4
388      3
389      5
390      2
391     14
392      3
393      5
394      6
395      6
396      3
397      1
398      8
399      3
400      2
401      6
402      4
403      4
404      3
405      2
406      3
407      2
408      3
409      2
410      4
411      1
412      2
413      6
414      2
415      4
416      4
417      3
418      4
419      2
420      9
421     10
422      5
423      1
424      3
425      3
426      5
427      4
428      6
429      4
430      3
431      5
432      6
433      4
434      1
435      2
436      3
437      2
438      3
439      3
440      2
441      2
442     13
443      1
444      4
445      4
446      3
448      3
449      1
450      9
451      5
452      2
453      2
454      3
455      4
456      3
457      7
458      3
459      5
460      4
461      5
462      2
463      2
464      2
465      7
466      9
467      3
468      3
469      4
470      4
471      5
472      4
473      1
474      3
475     10
476      2
477      4
478      3
479      2
480      1
481      1
482      3
483      1
484      4
485      2
486      6
487      1
488      1
489      3
490      2
491      1
492      2
493      2
494      3
495      4
496      2
497      5
498      3
499      7
500      5
501      6
502      3
503      2
504      3
505      2
506      4
507      3
508      6
509      3
510      6
511      1
512     11
513      1
514      3
515      1
516      1
517      2
518      3
519      2
520      4
521      1
523      3
524      3
525      5
526      2
527      3
528      2
529      4
530      5
531      4
532      4
533      5
534      5
535      5
536      3
537      7
538      3
539      4
540      3
541      3
542      3
543      1
544      3
545      1
546      2
547      8
549      2
550      5
551      4
552      3
553      5
554      1
555      2
556      1
557      1
558      4
559      1
560      1
561      4
562      1
563      2
564      3
565      4
566      2
567     10
568      1
569      3
570      1
571      1
572      5
573      1
574      4
575      2
576      1
577      4
578      5
579      1
580     11
581     12
582      2
583      1
584      5
585      3
586      3
587      4
588      2
589      5
590      9
591      1
592      3
593      1
594      2
595      1
596      1
597      5
598      1
599      2
600      4
601      1
602      8
603      2
604      3
605      4
606      3
607      4
608      3
609      4
610      5
611     17
612      3
613      2
614      2
615     10
616      5
617      4
618      1
619      2
620      2
622      3
623      2
624      5
625      5
626      5
627      5
628      7
629      4
630      2
631      3
632      4
633      3
634      3
635      2
636      3
637     10
638      5
639      4
640      1
641      3
642      2
643      4
644      5
645      7
646      6
647     20
648     20
649      5
650      6
651      7
652      9
653      8
654      5
655      5
656      3
657      3
658      4
659     12
660      4
661      5
662     14
663      5
664      4
665      5
666      3
667      4
668      6
669      4
670      4
671      9
672      9
673      6
674      5
675      4
676      4
677      4
678      6
679      6
680      4
681      2
682      3
683      6
684      6
685      9
686      4
687      3
688      3
689      4
690     16
691      1
692      4
693      4
694      4
695     12
696      3
697      4
698      4
699      7
700      9
701     11
702      6
703      6
704      4
705      3
706      3
707      4
708      5
709      4
710      3
711     12
712      9
713      7
714      8
715      4
716      3
717      6
718      6
719      4
720      5
721      5
722      2
723      6
724      4
725      5
726      3
727      4
728     12
729      4
730      4
731     12
732      7
733      9
734      1
735      2
736      7
737      7
738      4
739      8
740      4
741      8
742      4
743      4
744      3
745     12
746      5
747      5
748      7
749      4
750      3
751      4
752      4
753      5
754      6
755      6
756      4
757      3
758      8
759      3
760      5
761      4
762      5
763      5
764      6
765      5
766      7
767      6
768      7
769      5
770      3
771      4
772      4
785      4
786      8
787      8
788      6
789      6
790      5
791      8
792      6
793      4
794      4
795      7
796      7
797      3
798      4
799      4
800      3
801      2
802      6
803     16
804      5
805      6
806      5
807      3
808      4
809      4
810      5
811      9
812     12
813      4
814     12
815      4
816      5
817      4
818      4
819      5
820      5
821      4
822      7
823      5
825      5
826      5
827     12
828      6
829      7
830      8
831      9
832      4
833      4
834      5
835      5
836      4
837      3
838      9
839      6
840      3
841      9
842      3
843      8
844      9
845      5
846      4
848      3
849      4
850      4
851      8
852      8
853     12
854      4
855      3
856      3
857      3
858      7
859      3
860      3
861      9
862     12
863      4
864      4
865      4
866     18
867      3
868     10
869      9
870      3
871      3
872      3
873      4
874      7
875      6
876      5
877      4
878      4
879      4
880      8
881      4
882      5
883      7
884      9
885      5
886      8
887     18
888      4
889      4
890      4
891      4
892      3
893      5
894      4
895      3
896      3
897      5
898      5
899      3
900      2
901      3
902      5
903      4
904      4
905     16
906      3
907      4
908      4
909      4
910      5
911      6
912      4
913      3
914      5
915      5
916     16
917     12
918      4
919      5
920      5
921      8
922      5
923      7
924      7
925      6
926      7
927      7
928      3
929      5
930      5
931      4
932      5
933     12
934      3
935      4
936      4
937      9
938      9
939      7
940      4
941      4
942      5
943      9
944      4
945      4
946      2
947      4
948      4
949      4
950      9
951      6
952      9
953      3
954      4
955      5
956      4
957      4
958      6
959      5
960      3
961      6
962      3
963      4
964      4
965      4
966      3
967      5
968      4
969     12
970      6
971      4
972      3
973      6
974      4
975      3
976      3
977      6
978      4
979      7
980      4
981      5
982      4
983     12
984      8
985      4
986      5
987      4
988      6
989      4
990      5
991      8
992      4
993     13
994      5
995      4
996      4
997      6
998      4
999      4
1000     5
1001     6
1002     4
1003     8
1004     8
1005     2
1006     8
1007     6
1008     2
1009     4
1010     9
1011     7
1012     4
1013     3
1014    17
1015     6
1016     9
1017     4
1018     4
1019    12
1020     2
1021    11
1022     9
1023     4
1024     5
1025     6
1026     9
1027     4
1028     4
1029     4
1030     9
1031     3
1032     3
1033     6
1034     4
1035     5
1036     4
1037     3
1038     3
1039     4
1040     2
1041     3
1042     3
1043     3
Name: bathroom, dtype: int32

In [48]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Balcony

In [50]:
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [52]:
df['balcony'].isnull().sum()

0

In [56]:
df['balcony'].str.split(' ').str.get(0).str.replace('No', '0').sample(5)

529    3
750    2
677    3
22     3
383    2
Name: balcony, dtype: object

In [57]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No', '0')
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Additional Room

In [68]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [71]:
df['additionalRoom'].isnull().sum()

386

In [73]:
df['additionalRoom'].fillna('not available', inplace=True)

C:\Users\15105\AppData\Local\Temp\ipykernel_97756\3772747323.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available', inplace=True)

In [74]:
df['additionalRoom'] = df['additionalRoom'].str.lower()
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Floors

In [75]:
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
11 Floors      2
12 Floors      2
10 Floors      2
16 Floors      1
51 Floors      1
41 Floors      1
27 Floors      1
20 Floors      1
13 Floors      1
21 Floors      1
02 Floors      1
33 Floors      1
Name: count, dtype: int64

In [76]:
df['noOfFloor'].isnull().sum()

19

In [78]:
df['noOfFloor'].str.split(' ').str.get(0)

0         3
1         2
2         5
3         5
4         5
5         4
6         3
7         4
8         3
9         4
10        2
11        3
12        4
13        3
14        3
15        3
16        3
17        3
18        3
19        3
20        3
21        3
22        2
23      NaN
24        4
25        3
26        1
27        3
28        3
29        3
30        2
31        3
32        3
33        1
34        2
35        3
36        4
37        1
38        3
39        3
40        2
41        1
42        4
43        4
44        4
45        4
46        2
47        3
48        3
49        2
50        2
51      NaN
52        3
53        2
54        3
55        2
56        2
57        2
58        3
59        3
60        3
61        3
64        1
65        3
79        4
80        2
90        2
91        2
101       3
106       2
107       1
108       3
109       2
112       2
113       1
114       3
116       3
117       1
118       4
119       2
120       1
121       1
122       3
123       2
124       2
125       2
126       3
127       2
128       3
129       3
130       2
131       3
132       2
133       2
134       3
135       2
136       2
137       2
138       2
139       3
140       2
141       2
142       2
143       1
144       2
145       1
146       2
147       1
148       2
149       2
150       2
151       2
152       3
153       4
154       4
155       2
156       4
157       1
158       2
159       2
160       2
161       4
162       4
163       3
164       4
165       3
166       3
167       2
168     NaN
169       1
170       3
171       1
172       1
173       4
174       2
175       3
176       4
177       2
178       1
179       3
180       3
181       3
182       2
183       1
184       3
185      02
186       3
187       2
188       2
189       2
190       1
191       1
192       1
193       2
194       2
195       2
196       1
197       1
198       1
199       3
200       1
201       1
202       3
203       3
204       1
205       3
206      14
207      21
208       1
209       1
210       2
211       3
212       1
213       1
214       1
215       2
216       0
217     NaN
218       3
219       3
220       3
221       1
222       2
223       3
224       3
225       2
226       1
227       3
228       2
229       3
230       1
231       1
232       1
233       3
234       3
235     NaN
236       3
237       1
238       3
239      12
240       1
241       2
242       2
243       2
244       1
245       3
246     NaN
247       3
248       1
249       3
250       2
251       3
252       2
253       0
254       1
255       1
256       1
257       0
258       3
259       1
262       2
263       2
264       1
265       1
266       1
267       2
268      27
269       4
270       3
271       3
272       2
274       1
275       1
276       1
279       1
280       3
281       3
282       4
283       4
285       4
286       1
287       3
288       2
289       3
297       4
298       2
299       1
300       2
301       1
302       2
303       2
304       4
305       1
306       1
307       2
308       3
309       1
310       2
311       3
312      13
313       1
314       1
315       1
316       1
317       3
322       2
323       4
327     NaN
328       3
329       3
330       3
331       6
332       2
333       4
334       1
335       3
336       1
337       1
338       1
339       1
340       2
341       1
342       3
343       1
344       3
345       1
346       4
347       3
348       1
349       3
350     NaN
351       2
352       2
353       3
354       1
356       2
357       2
358       1
359       1
360       1
361       1
362       1
363       3
364       3
365       1
366       3
367       4
368       4
369       2
370     NaN
371       1
372       1
373       3
374       2
375       4
376       2
377       2
378       1
379       1
380       1
381       3
382       3
383       1
385       4
386       1
387       4
388       2
389       2
390       3
391       6
392       2
393       2
394       3
395       2
396       3
397       3
398       4
399       1
400       1
401       1
402       3
403       2
404       2
405       1
406       1
407       1
408       1
409       1
410       2
411       1
412       1
413       3
414       2
415       2
416       1
417       3
418       3
419       2
420       3
421       1
422       1
423       1
424       2
425       3
426       2
427       4
428       3
429       3
430       1
431      10
432       4
433       4
434       1
435       2
436       3
437       2
438       1
439       2
440       1
441       2
442       5
443       1
444       4
445       3
446       2
448       1
449       1
450       3
451       3
452       2
453       1
454      20
455       3
456       3
457       4
458       3
459       3
460       3
461       2
462       2
463       1
464       2
465       3
466       3
467       2
468       2
469       4
470       2
471       3
472       3
473       1
474       4
475       1
476       1
477       2
478       3
479       1
480       1
481       1
482       1
483       1
484       2
485       1
486       3
487       1
488       3
489       3
490       1
491       1
492       2
493       4
494       1
495       1
496       1
497       4
498       2
499       3
500       4
501       2
502       2
503       1
504       2
505       1
506       1
507       3
508       4
509       3
510       4
511       1
512       4
513     NaN
514       2
515       2
516       0
517       2
518       3
519       2
520       3
521       3
523       3
524       3
525       1
526       1
527       3
528      14
529       1
530       3
531       3
532       3
533       4
534      14
535      12
536       1
537       4
538       3
539       4
540       1
541       2
542       3
543       1
544       1
545       2
546       4
547     NaN
549       2
550       3
551       2
552       3
553       2
554       1
555       1
556       1
557       1
558       3
559       1
560       1
561       3
562       1
563       2
564       1
565       2
566       3
567       3
568       3
569       3
570       1
571       1
572       2
573       1
574       3
575      11
576       0
577       3
578       4
579       3
580       3
581       3
582       4
583       1
584       4
585       3
586       1
587       1
588       5
589       4
590      11
591       1
592       2
593       1
594      41
595       1
596       1
597       3
598       1
599       3
600       4
601       1
602       5
603       2
604       2
605       3
606       3
607       2
608       2
609       4
610       3
611       5
612       3
613       1
614       1
615       3
616       2
617       3
618       1
619     NaN
620       3
622       1
623       2
624       3
625       4
626       4
627       4
628       2
629       2
630       3
631       1
632       2
633       2
634       2
635       2
636       1
637       3
638       4
639       2
640       1
641       2
642       1
643       1
644       3
645       4
646       3
647       4
648       4
649       3
650       3
651       3
652       3
653       3
654       3
655       1
656       3
657       3
658       2
659       3
660       3
661       4
662     NaN
663       3
664       2
665       2
666       4
667       1
668       3
669       4
670       2
671       3
672       3
673       3
674       2
675       3
676       2
677       2
678       4
679      10
680       3
681       4
682       2
683       4
684       2
685       3
686       3
687       3
688       2
689       1
690       4
691       2
692       4
693       2
694       3
695       4
696       2
697       2
698       2
699       3
700       4
701       5
702       4
703       4
704       3
705       3
706       3
707       4
708       2
709       2
710       2
711       4
712       4
713      51
714       3
715       3
716       2
717       3
718       2
719       2
720       2
721       3
722       1
723       3
724       2
725       2
726       4
727       3
728       4
729       3
730       2
731       4
732       2
733       3
734       1
735       2
736       1
737       3
738       3
739       4
740       3
741       3
742       2
743       3
744       2
745       4
746       2
747       2
748       3
749       4
750       2
751       2
752       4
753       3
754       2
755       3
756       2
757       2
758       4
759       2
760       3
761       3
762       2
763       2
764       2
765       2
766       3
767       4
768       2
769       2
770       2
771       4
772       3
785     NaN
786       4
787       4
788       3
789       3
790       4
791       3
792       3
793       2
794       4
795       3
796       3
797       4
798       4
799       3
800       4
801       4
802       3
803       4
804       1
805       3
806       2
807       4
808     NaN
809       2
810       2
811       2
812       4
813       3
814       4
815     NaN
816       3
817       4
818     NaN
819       2
820       2
821       2
822       3
823       2
825       3
826       4
827       4
828       3
829       3
830       3
831       3
832       2
833       2
834       2
835       2
836      16
837       4
838       2
839       3
840       1
841       2
842       2
843       3
844       3
845       3
846       1
848       1
849       1
850       2
851       3
852       3
853       4
854       3
855       2
856       4
857       2
858       3
859       2
860       2
861       4
862       4
863       2
864       3
865       2
866       4
867       4
868       4
869       4
870       2
871       2
872       2
873       2
874       3
875       2
876       3
877       2
878       2
879       3
880       3
881       4
882       4
883       2
884       3
885       2
886       3
887       4
888       3
889       3
890       1
891       2
892       3
893       3
894       2
895       3
896       2
897       3
898       4
899       2
900       3
901       4
902       3
903       3
904       3
905       4
906       3
907       2
908       2
909       2
910       3
911       3
912       3
913       1
914       3
915       2
916       4
917       4
918       3
919       3
920       2
921       4
922       3
923       2
924       2
925       3
926       2
927       2
928       2
929       2
930       2
931       2
932       3
933       6
934       1
935       2
936       2
937       4
938       3
939       3
940       2
941       2
942       4
943       3
944       2
945       2
946       2
947       2
948       2
949       3
950       4
951       4
952       3
953       3
954       3
955       2
956     NaN
957       4
958       3
959       2
960       2
961       2
962       2
963       2
964       2
965       2
966       2
967       2
968       3
969     NaN
970       3
971       2
972       1
973       3
974       2
975       3
976       1
977       2
978       2
979       2
980       2
981       3
982       2
983       3
984       3
985       2
986       3
987      33
988       3
989       2
990       3
991       3
992       2
993       3
994       2
995       2
996       2
997       2
998       2
999       1
1000      3
1001      3
1002      3
1003      4
1004      4
1005      0
1006      4
1007      4
1008      2
1009      2
1010      3
1011      3
1012      2
1013      4
1014      4
1015      3
1016      3
1017      3
1018      2
1019      4
1020      3
1021      4
1022      5
1023      3
1024      2
1025      3
1026      2
1027      3
1028      2
1029      3
1030      3
1031      3
1032      2
1033      3
1034      3
1035      3
1036      2
1037      2
1038      2
1039      2
1040      2
1041      2
1042      2
1043      2
Name: noOfFloor, dtype: object

In [79]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [80]:
df.rename(columns={'noOfFloor':'floorNum'}, inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

### Facing

In [82]:
df['facing'].isnull().sum()

303

In [83]:
df['facing'].fillna('NA', inplace=True)

C:\Users\15105\AppData\Local\Temp\ipykernel_97756\1828012753.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA', inplace=True)

### Area 

feature_engineering

In [87]:
df['area'] = round((df['price'] * 10000000)/df['price_per_sqft'])

In [88]:
### Adding col property_type with house as all fields
df.insert(loc=1, column='property_type', value='house')
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [89]:
df.shape

(964, 20)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 1043
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int32
 8   bathroom         964 non-null    int32
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(3), int32(2), object(15)
memory usage: 150.6+ KB

In [91]:
df.to_csv('house_cleaned_level_1.csv', index=False)